import { Button, VerticalBox, HorizontalBox, Slider, ProgressIndicator } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <int> counter: 42;
    in property <string> song_name: "Song Name";
    in property <string> artist_name: "Artist Name";
    in property <string> album_name: "Album Name";
    in property <color> background_color: #CC0000FF;
    in property <bool> use_white_text: true;
    in property <bool> paused: true;
    in property <bool> shuffled: false;
    in property <bool> liked: false;
    in property <image> song_image: @image-url("./res/song_image.png");
    in property <image> rw: @image-url("./res/back_button.svg");
    in property <image> pause: @image-url("./res/pause_button.svg");
    in property <image> play: @image-url("./res/play_button.svg");
    in property <image> ff: @image-url("./res/forward_button.svg");
    in property <image> bg: @image-url("./res/background.png");
    in property <image> heart_off: @image-url("./res/heart_off.svg");
    in property <image> heart_on: @image-url("./res/heart_on.svg");
    in property <image> shuffle_off: @image-url("./res/shuffle_off.svg");
    in property <image> shuffle_on: @image-url("./res/shuffle_on.svg");

    out property <length> x-location: ta.mouse-x;

    in property <float> time: 0;

    callback skip-forward();
    callback skip-backward();
    callback play-pause();
    callback like();
    callback shuffle();
    callback refresh();
    callback seek();

    VerticalBox {
        padding: 0px;
        Rectangle {
            width: 800px;
            height: 480px;
            // Image {
            //     source: root.bg;
            //     width: 100%;
            //     height: 100%;
            //     visible: true;
            // }

            background: root.background_color.darker(0.05);

            VerticalBox {
                padding: 20px;
                padding-left: 0px;
                padding-right: 0px;
                HorizontalBox {
                    padding-left: 20px;
                    padding-right: 20px;
                    Rectangle {
                        clip: true;
                        drop-shadow-color: #000000;
                        drop-shadow-offset-x: 0px;
                        drop-shadow-offset-y: 0px;
                        drop-shadow-blur: 10px;
                        border-radius: 10px;
                        width: 280px;
                        height: 280px;
                        Button {
                            opacity: 0;
                            width: 100%;
                            height: 100%;
                            clicked => {
                                root.refresh();
                            }
                        }

                        Image {
                            source: root.song_image;
                            width: 100%;
                            height: 100%;
                            visible: true;
                        }
                    }

                    VerticalBox {
                        alignment: center;
                        Text {
                            text: root.song_name;
                            font-size: 40px;
                            font-weight: 12;
                            color: root.use_white_text ? #FFFFFFC8 : root.background_color.brighter(0.9);
                        }

                        Text {
                            text: root.artist_name;
                            font-size: 20px;
                            font-weight: 2;
                            color: root.use_white_text ? #CCCCCCC8 : root.background_color.brighter(0.8);
                        }

                        Text {
                            text: root.album_name;
                            font-size: 20px;
                            font-weight: 2;
                            color: root.use_white_text ? #EEEEEEC8 : root.background_color.brighter(0.85);
                        }
                    }
                }

                Rectangle {
                    background: root.background_color.darker(0.45);
                    width: 100%;
                    height: 100%;
                    padding: 0px;

                    Rectangle {
                        y: 0px;
                        background: root.background_color.darker(0.8);
                        width: 100%;
                        height: 5px;
                        padding: 0px;

                        ta := TouchArea {
                            width: 100%;
                            height: 5px;
                            clicked => {
                                root.seek();
                            }
                        }

                        bar := Rectangle {
                            x: 0px;
                            background: #FFFFFF;
                            width: root.time * 800px;
                            height: 5px;
                            padding: 0px;
                            animate width { duration: 100ms; }
                        }
                    }

                    HorizontalBox {
                        padding-top: 25px;
                        alignment: center;

                        width: 100%;
                        spacing: 50px;

                        Rectangle {

                            width: 100px;
                            height: 100px;
                            Button {
                                opacity: 0;
                                width: 100%;
                                height: 100%;
                                clicked => {
                                    root.shuffle();
                                }
                            }

                            Image {
                                source: (root.shuffled) ? root.shuffle_on : root.shuffle_off;
                                width: 100%;
                                height: 100%;
                                visible: true;
                            }
                        }

                        Rectangle {

                            width: 100px;
                            height: 100px;

                            Button {
                                opacity: 0;
                                width: 100%;
                                height: 100%;
                                clicked => {
                                    root.skip-backward();
                                }
                            }

                            Image {
                                source: root.rw;
                                width: 100%;
                                height: 100%;
                                visible: true;
                            }
                        }

                        Rectangle {

                            width: 100px;
                            height: 100px;

                            Button {
                                opacity: 0;
                                width: 100%;
                                height: 100%;
                                clicked => {
                                    root.play-pause();
                                }
                            }

                            Image {
                                source: (root.paused) ? root.pause : root.play;
                                width: 100%;
                                height: 100%;
                                visible: true;
                            }
                        }

                        Rectangle {

                            width: 100px;
                            height: 100px;

                            Button {
                                opacity: 0;
                                width: 100%;
                                height: 100%;
                                clicked => {
                                    root.skip-forward();
                                }
                            }

                            Image {
                                source: root.ff;
                                width: 100%;
                                height: 100%;
                                visible: true;
                            }
                        }

                        Rectangle {

                            width: 100px;
                            height: 100px;
                            Button {
                                opacity: 0;
                                width: 100%;
                                height: 100%;
                                clicked => {
                                    root.like();
                                }
                            }

                            Image {
                                source: (root.liked) ? root.heart_on : root.heart_off;
                                width: 100%;
                                height: 100%;
                                visible: true;
                            }
                        }
                    }
                }
            }
        }
    }
}
